  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  # 50
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController #effort_controllers
    joint: joint1
    pid: {p: 100.0, i: 0.1, d: 1.0}